pipeline {
    agent any
    environment {
        REPO_URL          = 'https://github.com/huynhminhchu/catalog-service.git'
        HARBOR_CREDENTIAL = credentials('harbor-credential')
    }
    stages {
        stage('Checkout'){
            steps {
                git branch: "master", url: env.REPO_URL

            }
        }

        stage('Test') {
            steps {
                sh 'ls -la'
            }
            // post {
            //     success {
            //         echo "Now Archiving the Artifacts....."
            //         archiveArtifacts artifacts: '**/*.jar'
            //     }
            // }
        }
        stage('Security Check') {
            steps {
                sh 'ls -la'
            }
            // post {
            //     success {
            //         echo "Now Archiving the Artifacts....."
            //         archiveArtifacts artifacts: '**/*.jar'
            //     }
            // }
        }
        stage('Build & Push') {
            steps {
                script {


                    env.GIT_COMMIT=sh(returnStdout: true, script: 'git rev-parse HEAD').trim()
                    sh 'env | sort'
                    // sh """
                    //     mvn -B -DskipTests clean package
                    //     docker build -t catalog-service:${env.GIT_COMMIT} .
                    // """

                    sh """#!/bin/bash
                    echo ${env.GIT_COMMIT}
                    echo "Current working directory"
                    ls -la
                    pwd
                    echo "Harbor user: $HARBOR_CREDENTIAL_USR"
                    /opt/maven/bin/mvn -B -DskipTests clean package
                    docker build -t harbor.chuhuynh.local/polarbookshop/catalog-service:${env.GIT_COMMIT} .
                    docker tag harbor.chuhuynh.local/polarbookshop/catalog-service:${env.GIT_COMMIT} harbor.chuhuynh.local/polarbookshop/catalog-service:latest
                    echo $HARBOR_CREDENTIAL_PSW | docker login harbor.chuhuynh.local:443 -u '$HARBOR_CREDENTIAL_USR' --password-stdin
                    """
                    
                }
            }
        }
    }
}