pipeline {
    agent any
    environment {
        REPO_URL          = 'https://github.com/huynhminhchu/catalog-service.git'
    }
    stages {
        stage('Checkout'){
            steps {
                dir("polar-bookshop") {
                    git(
                        url: "https://github.com/huynhminhchu/catalog-service.git",
                        branch: "master",
                        changelog: true,
                        poll: true
                    )
                }
            }
        }

        stage('Build') {
            steps {
                sh 'ls -la'
            }
            // post {
            //     success {
            //         echo "Now Archiving the Artifacts....."
            //         archiveArtifacts artifacts: '**/*.jar'
            //     }
            // }
        }
        stage('Test') {
            steps {
                sh 'mvn -f hello-app/pom.xml test'
            }
            post {
                always {
                    junit 'hello-app/target/surefire-reports/*.xml'
                }
            }
        }
    }
}