pipeline {
    agent any
    environment {
        REPO_URL          = 'https://github.com/huynhminhchu/catalog-service.git'
    }
    stages {
        stage('Checkout'){
            steps {
                dir("polar-bookshop") {
                    git branch: "master", url: env.REPO_URL
                }
            }
        }

        stage('Test') {
            steps {
                sh 'ls -la'
            }
            // post {
            //     success {
            //         echo "Now Archiving the Artifacts....."
            //         archiveArtifacts artifacts: '**/*.jar'
            //     }
            // }
        }
        stage('Security Check') {
            steps {
                dir("polar-bookshop") {
                    sh 'ls -la'
                }
            }
            // post {
            //     success {
            //         echo "Now Archiving the Artifacts....."
            //         archiveArtifacts artifacts: '**/*.jar'
            //     }
            // }
        }
        stage('Build') {
            steps {
                script {
                    dir("polar-bookshop/catalog-service") {

                        env.GIT_COMMIT=sh(returnStdout: true, script: 'git rev-parse HEAD').trim()
                        sh 'env | sort'
                        // sh """
                        //     mvn -B -DskipTests clean package
                        //     docker build -t catalog-service:${env.GIT_COMMIT} .
                        // """

                        sh """#!/bin/bash
                        echo ${env.GIT_COMMIT}
                        echo "Current working directory"
                        ls -la
                        pwd
                        mvn -B -DskipTests clean package
                        """
                    }
                }
            }
        }
    }
}